CREATE TABLE packs (
    id INTEGER NOT NULL PRIMARY KEY,
    title TEXT NOT NULL
);

CREATE TABLE cards (
    id INTEGER NOT NULL PRIMARY KEY,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    pack_id INTEGER NOT NULL REFERENCES packs(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE card_tags (
    card_id INTEGER NOT NULL REFERENCES cards(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    tag TEXT NOT NULL COLLATE NOCASE,
    PRIMARY KEY (card_id, tag)
) WITHOUT ROWID;

CREATE INDEX tag_index ON card_tags (tag);
