// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Card { id: bigint, label: string, script: string, template: string, pack_id: bigint, }