// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Card { id: number, label: string, script: string | null, front: string, back: string, }