// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DealerFilter { id: number, label: string, pack_title: string, weight: number, }