// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupedWeightedFilters } from "./GroupedWeightedFilters";

export interface Dealer { title: string, filters: GroupedWeightedFilters, }