// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tag } from "./Tag";

export interface Filter { label: string, pack_id: number, tags: Array<Tag>, is_valid: boolean, }