// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FullPrompt { card_id: number, front: string, back: string, tags: Array<string>, }