// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeightedFilter } from "./WeightedFilter";

export type GroupedWeightedFilters = Record<string, Array<WeightedFilter>>;