// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModifyStudy = { Rename: string } | { SetPack: number | null } | { SetLimit: number } | { AddIncluded: string } | { RemoveIncluded: string } | { AddExcluded: string } | { RemoveExcluded: string } | "Delete";