// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModifyCard = { AddTag: string } | { RemoveTag: string } | { Rename: { front: string | null, back: string | null, } };