// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModifyCard = { Edit: { label: string | null, script: string | null, template: string | null, } } | "Delete";