// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardSummary } from "./CardSummary";

export interface Pack { title: string, cards: Array<CardSummary>, }