// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardSummary } from "./CardSummary";
import type { FilterSummary } from "./FilterSummary";

export interface Pack { title: string, cards: Array<CardSummary>, filters: Array<FilterSummary>, invalid_filters: Array<number>, }