// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Completeness } from "./Completeness";

export interface Question { question: string, answer: string, status: Completeness, }