// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Question } from "./Question";

export interface Quiz { id: string, name: string, questions: Array<Question>, }