// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuizQuery } from "./QuizQuery";

export interface QuizSummary { id: QuizQuery, name: string, }